# Generated by Django 5.2.8 on 2025-11-27 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(help_text='Your comment', max_length=2000),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('oops', '🤦 Oops I Did It Again'), ('pets', '🐾 Pet Nonsense'), ('existential', '🤔 Existential Dread'), ('shower', '🚿 Shower Thoughts'), ('brain', '💨 Brain Farts'), ('plot', '🎬 Plot Twists')], max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(help_text='The full content of your post', max_length=5000),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='Catchy title for your thought', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='vibe',
            field=models.CharField(choices=[('chaotic', '🌪️ Chaotic'), ('silly', '🤪 Silly'), ('existential', '🤯 Existential'), ('mindblowing', '💡 Mindblowing')], max_length=20),
        ),
    ]
